// 50 launch categories. Kept flat and stable so bids stay comparable over time.
export const CATEGORIES: string[] = [
  "AI & Machine Learning",
  "Developer Tools",
  "SaaS",
  "Productivity",
  "Design Tools",
  "No-Code / Low-Code",
  "Marketing",
  "Sales & CRM",
  "Analytics & Data",
  "Fintech",
  "Crypto & Web3",
  "E-commerce",
  "Marketplaces",
  "Social",
  "Community",
  "Newsletters & Media",
  "Education",
  "Health & Fitness",
  "Mental Health",
  "Food & Drink",
  "Travel",
  "Real Estate",
  "Hardware",
  "IoT & Robotics",
  "Games",
  "AR / VR",
  "Music & Audio",
  "Video",
  "Photography",
  "Writing Tools",
  "Customer Support",
  "HR & Recruiting",
  "Legal Tech",
  "Security & Privacy",
  "DevOps & Infra",
  "Databases",
  "APIs",
  "Browser Extensions",
  "Mobile Apps",
  "Desktop Apps",
  "Open Source",
  "Automation",
  "Project Management",
  "Customer Data",
  "Localization",
  "Accessibility",
  "Sustainability & Climate",
  "Nonprofit",
  "Family & Kids",
  "Other",
];

export function isValidCategory(c: string): boolean {
  return CATEGORIES.includes(c);
}
